### PR TITLE
Memoize cql exec fhir

### PR DESCRIPTION
**Pull request by mrnosal**
merged with latest pilot updates.
Add debugging CDS Apply display to bottom of recommendation.
Remove BundleAnalyzer plugin from build - minor speedup

### CODE REVIEW

**Comment by mickohanlon23** [comment]
Hey @mrnosal, the memoizer branch of our cql-exec-fhir fork was merged into pilot yesterday via https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/59/files. What is the goal of this PR here? To allow our pilot partners to see the apply time in the dashboard as they are testing?

**Review by mickohanlon23 — COMMENTED** [review]
Hey @mrnosal, the memoizer branch of our cql-exec-fhir fork was merged into pilot yesterday via https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/59/files. What is the goal of this PR here? To allow our pilot partners to see the apply time in the dashboard as they are testing?

**Comment by mrnosal** [comment]
At first I thought you were waiting for a PR from this branch. I had added the timing for easier debugging. We can hold for now.

**Comment by mickohanlon23** [comment]
Okay. I recognized this branch as I had used it for testing earlier this week. But I thought it was a tool for our own internal testing, rather than something we want to send to our pilot site. Let me know if I am incorrect in that assumption.

For now, do you want to close this PR, but keep the branch existent, and make note of it somewhere (maybe on Jira) that this branch can be used to help with Dashboard performance testing?

**Comment by mickohanlon23** [comment]
Closing this PR, as it is OBE. I will keep the `memoize-cql-exec-fhir` branch open, if we would like to use the added "_Apply time:_" in the Dashboard display for future performance investigations.

**Pull request closed without merging**
